services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=job-service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=job-service'
    ports:
      - '13551:5432'
