spring:
  datasource:
    url: jdbc:postgresql://localhost:13551/job-service
    username: job-service
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

  docker:
    compose:
      skip:
        in-tests: false